import type { CSSProperties } from "react";

/** Co-located styles for CommunitySkillsDrawer. */
export const s = {
  search: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    marginBottom: 14,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 14,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  chipRow: { display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 20 } satisfies CSSProperties,
  chip: (active: boolean): CSSProperties => ({
    padding: "5px 12px",
    borderRadius: 99,
    fontSize: 12.5,
    fontWeight: 600,
    border: "1px solid " + (active ? "var(--accent)" : "var(--border)"),
    background: active ? "var(--accent-bg)" : "var(--bg-elevated)",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
    cursor: "pointer",
  }),
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 12 } satisfies CSSProperties,
  card: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  cardHeader: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  cardName: { fontSize: 14, fontWeight: 650, flex: 1, fontFamily: "var(--font-mono, monospace)" } satisfies CSSProperties,
  stars: { display: "flex", alignItems: "center", gap: 4, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  desc: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.45, flex: 1 } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
} as const;
