import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer + its File/URL tab panes. */
export const s = {
  tabsBar: { marginBottom: 20 } satisfies CSSProperties,
  section: { marginBottom: 22 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 10,
  } satisfies CSSProperties,
  dropzone: (dragOver: boolean): CSSProperties => ({
    border: "1.5px dashed " + (dragOver ? "var(--accent)" : "var(--border-strong)"),
    borderRadius: 9,
    background: dragOver ? "var(--accent-bg)" : "var(--bg-elevated)",
    padding: "28px 16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    textAlign: "center",
    cursor: "pointer",
    transition: "background .12s, border-color .12s",
  }),
  dropzoneHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "20px 0",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  dividerLine: { flex: 1, height: 1, background: "var(--border)" } satisfies CSSProperties,
  actions: { display: "flex", gap: 10, marginTop: 14, justifyContent: "flex-end" } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)", marginTop: 10 } satisfies CSSProperties,
  previewWrap: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  previewCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 16,
    background: "var(--bg-elevated)",
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  ignoredNotice: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    fontSize: 13,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  ignoredList: { margin: "4px 0 0", paddingLeft: 18, fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  statusNote: (color: string, bg: string): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 12px",
    borderRadius: 7,
    background: bg,
    color,
    fontSize: 13,
  }),
} as const;
