import type { CSSProperties } from "react";

/** Co-located styles for ContextTab. Mirrors SkillsTab/styles.ts's shape,
   plus a footer row for the "≈ N tokens" estimate and a missing-file
   indicator style. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    width: 200,
  } satisfies CSSProperties,
  filterIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 16, lineHeight: 1.45 } satisfies CSSProperties,
  list: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  row: (dragOver: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
    background: dragOver ? "var(--bg-hover)" : "transparent",
  }),
  handle: { display: "flex", cursor: "grab", color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  path: { fontSize: 13, flex: 1, minWidth: 0 } satisfies CSSProperties,
  missing: { fontSize: 11, color: "var(--crit)", display: "flex", alignItems: "center", gap: 4 } satisfies CSSProperties,
  empty: { padding: "24px 14px", fontSize: 13, color: "var(--text-muted)", textAlign: "center" } satisfies CSSProperties,
  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    padding: "8px 4px",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  previewBody: {
    padding: 20,
    fontSize: 13,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  previewLoading: { padding: 20 } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
} as const;
